<a href="https://colab.research.google.com/github/joaopedrodias07/wave_height_forecast/blob/master/leitura_variaveis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
library("ncdf4")
library("tidyverse")
library("lubridate")

In [ ]:
inspecionar_nc <- function(arquivo) {
  cat("\n", paste(rep("=", 50), collapse=""), "\n")
  cat("ARQUIVO:", arquivo, "\n")

  nc <- nc_open(arquivo)

  cat("\nVARIÁVEIS:\n")
  for (var in names(nc$var)) {
    v <- nc$var[[var]]
    cat(sprintf("  %s | %s | unidade: %s\n",
                var, v$longname, v$units))
  }

  cat("\nDIMENSÕES:\n")
  for (dim in names(nc$dim)) {
    d <- nc$dim[[dim]]
    cat(sprintf("  %s | tamanho: %d\n", dim, d$len))
  }

  nc_close(nc)
}

In [ ]:
arquivos <- list.files(pattern = "\\.nc$")
cat("Arquivos encontrados:", length(arquivos), "\n")
for (arq in arquivos) inspecionar_nc(arq)

Arquivos encontrados: 9

 ==================================================
ARQUIVO: variavel1.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  u10 | 10 metre U wind component | unidade: m s**-1

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 2

 ==================================================
ARQUIVO: variavel2.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  v10 | 10 metre V wind component | unidade: m s**-1

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 2

 ==================================================
ARQUIVO: variavel3.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  pp1d | Peak wave period | unidade: s

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 1

 ==================================================
ARQUIVO: variavel4.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  msl | Mean sea level pressure | unidade: Pa

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 2

 ==================================================
ARQUIVO: variavel5.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  mwd | Mean wave direction | unidade: Degree true

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 1

 ==================================================
ARQUIVO: variavel6.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  cdww | Coefficient of drag with waves | unidade: dimensionless

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 1

 ==================================================
ARQUIVO: variavel7.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  wss | Wave Spectral Skewness | unidade: Numeric

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 1

 ==================================================
ARQUIVO: variavel8.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  msqs | Mean square slope of waves | unidade: dimensionless

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 1

 ==================================================
ARQUIVO: variavel9.nc

VARIÁVEIS:
  number | ensemble member numerical id | unidade: 1
  expver | expver | unidade:
  hmax | Envelop-maximum individual wave height | unidade: m

DIMENSÕES:
  valid_time | tamanho: 8760
  latitude | tamanho: 1
  longitude | tamanho: 1

In [ ]:
nc <- nc_open("variavel1.nc")
lat <- ncvar_get(nc, "latitude")
lon <- ncvar_get(nc, "longitude")
nc_close(nc)

cat("Latitudes:", lat, "\n")
cat("Longitudes:", lon, "\n")

# Santos: -23.93, -46.33
santos_lat <- -23.93
santos_lon <- -46.33

# Distância só na longitude pois latitude tem só 1 ponto
dist_lon <- abs(lon - santos_lon)
idx_lon  <- which.min(dist_lon)

cat("\nDistâncias para Santos:\n")
cat(sprintf("  lon=%.2f → distância=%.4f\n", lon[1], dist_lon[1]))
cat(sprintf("  lon=%.2f → distância=%.4f\n", lon[2], dist_lon[2]))
cat(sprintf("\nPonto mais próximo: longitude %.2f (índice %d)\n",
            lon[idx_lon], idx_lon))

Latitudes: -24
Longitudes: -46.5 -46.25

Distâncias para Santos:
  lon=-46.50 → distância=0.1700
  lon=-46.25 → distância=0.0800

Ponto mais próximo: longitude -46.25 (índice 2)

In [ ]:
ponto_mais_proximo <- function(arquivo, santos_lat = -23.93, santos_lon = -46.33) {

  nc <- nc_open(arquivo)
  lat <- ncvar_get(nc, "latitude")
  lon <- ncvar_get(nc, "longitude")
  nc_close(nc)

  # Encontrar índices mais próximos
  idx_lat <- which.min(abs(lat - santos_lat))
  idx_lon <- which.min(abs(lon - santos_lon))

  cat(sprintf("Arquivo: %s\n", arquivo))
  cat(sprintf("  Ponto mais próximo → lat: %.4f (idx=%d) | lon: %.4f (idx=%d)\n",
              lat[idx_lat], idx_lat,
              lon[idx_lon], idx_lon))

  return(list(
    lat     = lat[idx_lat],
    lon     = lon[idx_lon],
    idx_lat = idx_lat,
    idx_lon = idx_lon
  ))
}

In [ ]:
arquivos <- list.files(pattern = "\\.nc$")
for (arq in arquivos) ponto_mais_proximo(arq)

Arquivo: variavel1.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.2500 (idx=2)
Arquivo: variavel2.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.2500 (idx=2)
Arquivo: variavel3.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.5000 (idx=1)
Arquivo: variavel4.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.2500 (idx=2)
Arquivo: variavel5.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.5000 (idx=1)
Arquivo: variavel6.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.5000 (idx=1)
Arquivo: variavel7.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.5000 (idx=1)
Arquivo: variavel8.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.5000 (idx=1)
Arquivo: variavel9.nc
  Ponto mais próximo → lat: -24.0000 (idx=1) | lon: -46.5000 (idx=1)

In [ ]:
ler_nc <- function(arquivo) {
  nc <- nc_open(arquivo)

  # Definições dentro da função
  santos_lat   <- -23.93
  santos_lon   <- -46.33
  vars_ignorar <- c("number", "expver")

  # Coordenadas
  lat <- ncvar_get(nc, "latitude")
  lon <- ncvar_get(nc, "longitude")
  idx_lat <- which.min(abs(lat - santos_lat))
  idx_lon <- which.min(abs(lon - santos_lon))

  # Tempo
  tempo_raw <- ncvar_get(nc, "valid_time")
  datetime  <- as.POSIXct(tempo_raw, origin = "1970-01-01", tz = "UTC")

  # Variável principal
  nome_var  <- names(nc$var)[!names(nc$var) %in% vars_ignorar][1]
  dados_raw <- ncvar_get(nc, nome_var)

  # Extrair valores conforme dimensão do array
  if (is.matrix(dados_raw)) {
    # dimensão: 2 x 8760 — extrai a linha do ponto mais próximo
    valores <- dados_raw[idx_lon, ]
  } else {
    # dimensão: 8760 — vetor simples, usa direto
    valores <- as.numeric(dados_raw)
  }

  nc_close(nc)

  cat(sprintf("✓ %-6s | lat=%.2f lon=%.2f | %d obs\n",
              nome_var, lat[idx_lat], lon[idx_lon], length(valores)))

  tibble(
    datetime    = datetime,
    !!nome_var := as.numeric(valores)
  )
}

In [ ]:
arquivos <- list.files(pattern = "\\.nc$")

df_final <- arquivos %>%
  map(ler_nc) %>%
  reduce(full_join, by = "datetime") %>%
  arrange(datetime)

✓ u10    | lat=-24.00 lon=-46.25 | 8760 obs
✓ v10    | lat=-24.00 lon=-46.25 | 8760 obs
✓ pp1d   | lat=-24.00 lon=-46.50 | 8760 obs
✓ msl    | lat=-24.00 lon=-46.25 | 8760 obs
✓ mwd    | lat=-24.00 lon=-46.50 | 8760 obs
✓ cdww   | lat=-24.00 lon=-46.50 | 8760 obs
✓ wss    | lat=-24.00 lon=-46.50 | 8760 obs
✓ msqs   | lat=-24.00 lon=-46.50 | 8760 obs
✓ hmax   | lat=-24.00 lon=-46.50 | 8760 obs

In [ ]:
# ── Verificação ───────────────────────────────────────────────
cat("\nDimensões:", nrow(df_final), "x", ncol(df_final), "\n")
cat("Período:", format(min(df_final$datetime), "%Y-%m-%d %H:%M"),
    "a", format(max(df_final$datetime), "%Y-%m-%d %H:%M"), "\n")
cat("\nDados faltantes:\n")
print(colSums(is.na(df_final)))
cat("\nPrimeiras linhas:\n")
print(head(df_final))
glimpse(df_final)

Dimensões: 8760 x 10
Período: 2025-01-01 00:00 a 2025-12-31 23:00

Dados faltantes:
datetime      u10      v10     pp1d      msl      mwd     cdww      wss
       0        0        0        0        0        0        0        0
    msqs     hmax
       0        0

Primeiras linhas:
# A tibble: 6 × 10
  datetime              u10    v10  pp1d     msl   mwd     cdww    wss    msqs
  <dttm[1d]>          <dbl>  <dbl> <dbl>   <dbl> <dbl>    <dbl>  <dbl>   <dbl>
1 2025-01-01 00:00:00 -4.26 -0.587  9.93 101335.  150. 0.000841 0.0130 0.00343
2 2025-01-01 01:00:00 -4.15 -0.522  9.97 101353.  150. 0.000838 0.0130 0.00340
3 2025-01-01 02:00:00 -4.12 -0.621  9.99 101354.  149. 0.000815 0.0130 0.00337
4 2025-01-01 03:00:00 -3.68 -0.777 10.0  101296.  149. 0.000773 0.0131 0.00332
5 2025-01-01 04:00:00 -3.09 -0.552 10.0  101252.  149. 0.000724 0.0131 0.00325
6 2025-01-01 05:00:00 -2.45 -0.197 10.0  101234.  148. 0.000687 0.0130 0.00313
# ℹ 1 more variable: hmax <dbl>
Rows: 8,760
Columns: 10
$ datetime <dttm[1d]> <POSIXct[26]>
$ u10      <dbl> -4.2586823, -4.1511536, -4.1249237, -3.6797485, -3.09075…
$ v10      <dbl> -0.587051392, -0.522460938, -0.621185303, -0.777221680, -0.55…
$ pp1d     <dbl> 9.932961, 9.966652, 9.993019, 10.013039, 10.027199, 10.036476…
$ msl      <dbl> 101335.4, 101352.9, 101354.5, 101295.8, 101251.7, 101234.1, 1…
$ mwd      <dbl> 150.3298, 149.8325, 149.3564, 148.8990, 148.5655, 148.4647, 1…
$ cdww     <dbl> 0.0008412045, 0.0008383510, 0.0008151513, 0.0007729949, 0.000…
$ wss      <dbl> 0.01300998, 0.01302727, 0.01304291, 0.01305439, 0.01305060, 0…
$ msqs     <dbl> 0.003429498, 0.003404713, 0.003365618, 0.003316987, 0.0032454…
$ hmax     <dbl> 2.337203, 2.352866, 2.365037, 2.373783, 2.378024, 2.374745, 2…

In [ ]:
df_final

     datetime            u10         v10          pp1d      msl      mwd
1    2025-01-01 00:00:00 -4.2586823  -0.587051392  9.932961 101335.4 150.3298
2    2025-01-01 01:00:00 -4.1511536  -0.522460938  9.966652 101352.9 149.8325
3    2025-01-01 02:00:00 -4.1249237  -0.621185303  9.993019 101354.5 149.3564
4    2025-01-01 03:00:00 -3.6797485  -0.777221680 10.013039 101295.8 148.8990
5    2025-01-01 04:00:00 -3.0907593  -0.552154541 10.027199 101251.7 148.5655
6    2025-01-01 05:00:00 -2.4466400  -0.196594238 10.036476 101234.1 148.4647
7    2025-01-01 06:00:00 -2.1089630  -0.338851929 10.041359 101198.0 148.6026
8    2025-01-01 07:00:00 -1.6513062  -0.528015137 10.041359 101182.9 148.9300
9    2025-01-01 08:00:00 -0.7988892   0.003189087 10.037453 101189.1 149.3990
10   2025-01-01 09:00:00 -0.8914642   0.183731079 10.030128 101261.8 149.9300
11   2025-01-01 10:00:00 -1.4614410   0.084167480 10.014015 101323.4 150.5161
12   2025-01-01 11:00:00 -1.6911621   0.054153442 10.002785 101347.1 151.0315
13   2025-01-01 12:00:00 -1.5806580   0.557922363  9.989601 101380.1 151.5395
14   2025-01-01 13:00:00 -1.9770966   1.602416992  9.973488 101399.7 152.0368
15   2025-01-01 14:00:00 -2.7423706   2.414779663  9.954933 101382.8 152.4778
16   2025-01-01 15:00:00 -3.4301453   2.936904907  9.933937 101348.1 152.8453
17   2025-01-01 16:00:00 -3.6418915   2.271697998  9.910500 101324.1 153.1311
18   2025-01-01 17:00:00 -3.4194489   1.458572388  9.884132 101250.5 153.2934
19   2025-01-01 18:00:00 -3.7754211   1.733474731  9.897804 101204.5 153.3527
20   2025-01-01 19:00:00 -4.4163055   1.224960327  9.867043 101137.6 153.2701
21   2025-01-01 20:00:00 -4.3214417   0.488708496  9.833839 101139.4 153.0331
22   2025-01-01 21:00:00 -4.4897919   0.174804688  9.797218 101132.8 152.3785
23   2025-01-01 22:00:00 -4.2458038  -0.435714722  9.752785 101136.4 151.3797
24   2025-01-01 23:00:00 -3.8676147  -0.860610962  9.709816 101238.2 150.1601
25   2025-01-02 00:00:00 -3.9494629  -1.009735107  9.657570 101254.3 148.6965
26   2025-01-02 01:00:00 -3.8662720  -1.120086670  9.580421 101327.4 146.9465
27   2025-01-02 02:00:00 -3.1486511  -1.112045288  9.512062 101286.0 144.9533
28   2025-01-02 03:00:00 -2.7303772  -1.219512939  9.451027 101251.2 142.9726
29   2025-01-02 04:00:00 -1.8917999  -1.383636475  9.396828 101174.0 141.1992
30   2025-01-02 05:00:00 -1.2736664  -1.458953857  9.347511 101111.0 139.6813
⋮    ⋮                   ⋮           ⋮            ⋮         ⋮        ⋮
8731 2025-12-30 18:00:00 -4.79200745  3.59104919   5.639503 100890.3 140.0035
8732 2025-12-30 19:00:00 -4.33520508  3.31842041   5.624367 100932.1 141.6172
8733 2025-12-30 20:00:00 -4.06106567  2.88200378  17.508881 100935.1 143.5626
8734 2025-12-30 21:00:00 -3.78321838  2.47007751  17.499603 101039.8 146.4144
8735 2025-12-30 22:00:00 -3.15728760  1.68859863  17.462006 101008.8 149.9230
8736 2025-12-30 23:00:00 -3.25012207  1.47756958  17.409027 101091.4 153.8786
8737 2025-12-31 00:00:00 -3.73449707  1.37515259  17.339935 101194.1 157.6411
8738 2025-12-31 01:00:00 -3.65496826  0.51901245  17.258148 101290.1 160.8641
8739 2025-12-31 02:00:00 -2.89140320 -0.32914734  17.160492 101277.0 163.5247
8740 2025-12-31 03:00:00 -1.74871826 -0.90039062  16.987640 101264.5 165.7450
8741 2025-12-31 04:00:00 -0.46391296 -1.15187073  16.807953 101210.2 167.5977
8742 2025-12-31 05:00:00  0.44990540 -1.25526428  16.646820 101100.6 169.1581
8743 2025-12-31 06:00:00  0.25561523 -0.91879272  16.501801 101086.4 170.4596
8744 2025-12-31 07:00:00 -0.46014404 -0.74626160  16.368500 101102.6 171.5121
8745 2025-12-31 08:00:00 -0.05056763 -0.47917175  16.244476 101127.2 172.3488
8746 2025-12-31 09:00:00  1.11471558  0.17048645  16.125336 101203.1 173.0180
8747 2025-12-31 10:00:00  1.61135864 -1.18273926  16.010590 101219.7 173.5168
8748 2025-12-31 11:00:00  1.03512573 -1.07684326  15.886574 101262.1 173.8685
8749 2025-12-31 12:00:00  0.56065369  0.52722168  15.758156 101330.4 174.0972
8750 2025-12-31 13:00:00 -0.45092773  1.14788818  15.616066 101330.9 174.2180
8751 2025-12-31 14:00:00 -1.16340637  1.56027222  15.366554 101337.3 174.2664
8752 2025-12-31 15:00:00 -2.59927368  2.26141357  15.142921 101266.6 174.2381
8753 2025-12-31 16:00:00 -2.49987793  1.32003784  14.967628 101220.7 174.1648
8754 2025-12-31 17:00:00 -2.61531067  0.57402039  14.822609 101071.2 174.0742
8755 2025-12-31 18:00:00 -2.57968140  0.72981262  14.695656 101031.8 173.9792
8756 2025-12-31 19:00:00 -2.88903809  1.60755920  14.579933 100959.0 173.8674
8757 2025-12-31 20:00:00 -2.69845581  2.51718140  14.468605 100927.4 173.7637
8758 2025-12-31 21:00:00 -0.89096069  1.96078491  14.357765 100975.6 173.6564
8759 2025-12-31 22:00:00  0.43595886  1.30622864  14.234230 101070.2 173.6107
8760 2025-12-31 23:00:00  0.93772888  0.01014709  14.074074 101127.8 173.5101
     cdww         wss         msqs        hmax
1    0.0008412045 0.01300998  0.003429498 2.337203
2    0.0008383510 0.01302727  0.003404713 2.352866
3    0.0008151513 0.01304291  0.003365618 2.365037
4    0.0007729949 0.01305439  0.003316987 2.373783
5    0.0007244621 0.01305060  0.003245468 2.378024
6    0.0006870215 0.01302527  0.003131984 2.374745
7    0.0006861491 0.01297547  0.002982760 2.364781
8    0.0006851763 0.01290855  0.002824101 2.349154
9    0.0006843021 0.01282473  0.002667530 2.329506
10   0.0006831507 0.01273299  0.002522519 2.307474
11   0.0006824150 0.01264228  0.002341528 2.280625
12   0.0006828089 0.01253483  0.002232658 2.254695
13   0.0006825393 0.01242289  0.002126784 2.227674
14   0.0007382401 0.01231603  0.002064782 2.201085
15   0.0008042757 0.01221640  0.002086096 2.177788
16   0.0008544493 0.01212708  0.002147138 2.156590
17   0.0008660804 0.01204030  0.002215802 2.135163
18   0.0008323705 0.01195460  0.002222483 2.111593
19   0.0008215085 0.01197778  0.002231121 2.120798
20   0.0008303574 0.01190518  0.002249812 2.098122
21   0.0008164290 0.01184608  0.002269841 2.077017
22   0.0008633961 0.01182673  0.002420525 2.064839
23   0.0008378467 0.01183352  0.002521845 2.052023
24   0.0008116497 0.01187013  0.002599856 2.044648
25   0.0008242335 0.01193889  0.002666589 2.037564
26   0.0008150144 0.01208065  0.002751449 2.033274
27   0.0007651835 0.01221787  0.002806745 2.030068
28   0.0007230989 0.01232868  0.002800077 2.024197
29   0.0006861479 0.01239700  0.002741109 2.012228
30   0.0006851591 0.01242778  0.002642247 1.994649
⋮    ⋮            ⋮           ⋮           ⋮
8731 0.0009159511 0.021245345 0.002494744 1.296308
8732 0.0008897071 0.022275381 0.002684304 1.361339
8733 0.0008551853 0.003351499 0.002764827 1.413871
8734 0.0008175815 0.003550964 0.002792520 1.497633
8735 0.0007466022 0.003790847 0.002732946 1.593798
8736 0.0007786809 0.004081342 0.002742313 1.707531
8737 0.0007078215 0.004418921 0.002783044 1.836751
8738 0.0006881021 0.004806168 0.002851439 1.981936
8739 0.0006872492 0.005233526 0.002910180 2.137300
8740 0.0006862660 0.005713724 0.002934147 2.296642
8741 0.0006836883 0.006212350 0.002918125 2.453346
8742 0.0006799977 0.006707869 0.002875311 2.606580
8743 0.0006782392 0.007186130 0.002812142 2.753747
8744 0.0006782603 0.007641751 0.002731694 2.887754
8745 0.0006782189 0.008069865 0.002646344 3.009205
8746 0.0006779642 0.008465938 0.002565803 3.116986
8747 0.0006780056 0.008829236 0.002439908 3.209051
8748 0.0006779083 0.009167053 0.002365416 3.290050
8749 0.0006781088 0.009475261 0.002291542 3.356551
8750 0.0006795132 0.009758003 0.002219885 3.408494
8751 0.0007009245 0.010101654 0.002156680 3.448408
8752 0.0007882104 0.010401815 0.002226342 3.483616
8753 0.0008248843 0.010627739 0.002243512 3.500762
8754 0.0007681062 0.010793094 0.002229285 3.506532
8755 0.0007739540 0.010908384 0.002164675 3.499983
8756 0.0007653476 0.010984641 0.002124407 3.485201
8757 0.0006814105 0.011029039 0.002044173 3.459668
8758 0.0006818185 0.011047643 0.001953412 3.426308
8759 0.0006778208 0.011064239 0.001798966 3.385864
8760 0.0006779630 0.011098921 0.001742804 3.341418

In [ ]:
colnames(df_final) <- c("data_hora", "vento_u", "vento_v",
                         "periodo_onda_pico", "pressao_media_mar",
                         "direcao_media_onda", "coef_arrasto_onda",
                          "assimetria_espectral_onda", "inclinacao_media_quadratica_onda", "altura_maxima_onda")

In [ ]:
df_final

     data_hora           vento_u     vento_v      periodo_onda_pico
1    2025-01-01 00:00:00 -4.2586823  -0.587051392  9.932961
2    2025-01-01 01:00:00 -4.1511536  -0.522460938  9.966652
3    2025-01-01 02:00:00 -4.1249237  -0.621185303  9.993019
4    2025-01-01 03:00:00 -3.6797485  -0.777221680 10.013039
5    2025-01-01 04:00:00 -3.0907593  -0.552154541 10.027199
6    2025-01-01 05:00:00 -2.4466400  -0.196594238 10.036476
7    2025-01-01 06:00:00 -2.1089630  -0.338851929 10.041359
8    2025-01-01 07:00:00 -1.6513062  -0.528015137 10.041359
9    2025-01-01 08:00:00 -0.7988892   0.003189087 10.037453
10   2025-01-01 09:00:00 -0.8914642   0.183731079 10.030128
11   2025-01-01 10:00:00 -1.4614410   0.084167480 10.014015
12   2025-01-01 11:00:00 -1.6911621   0.054153442 10.002785
13   2025-01-01 12:00:00 -1.5806580   0.557922363  9.989601
14   2025-01-01 13:00:00 -1.9770966   1.602416992  9.973488
15   2025-01-01 14:00:00 -2.7423706   2.414779663  9.954933
16   2025-01-01 15:00:00 -3.4301453   2.936904907  9.933937
17   2025-01-01 16:00:00 -3.6418915   2.271697998  9.910500
18   2025-01-01 17:00:00 -3.4194489   1.458572388  9.884132
19   2025-01-01 18:00:00 -3.7754211   1.733474731  9.897804
20   2025-01-01 19:00:00 -4.4163055   1.224960327  9.867043
21   2025-01-01 20:00:00 -4.3214417   0.488708496  9.833839
22   2025-01-01 21:00:00 -4.4897919   0.174804688  9.797218
23   2025-01-01 22:00:00 -4.2458038  -0.435714722  9.752785
24   2025-01-01 23:00:00 -3.8676147  -0.860610962  9.709816
25   2025-01-02 00:00:00 -3.9494629  -1.009735107  9.657570
26   2025-01-02 01:00:00 -3.8662720  -1.120086670  9.580421
27   2025-01-02 02:00:00 -3.1486511  -1.112045288  9.512062
28   2025-01-02 03:00:00 -2.7303772  -1.219512939  9.451027
29   2025-01-02 04:00:00 -1.8917999  -1.383636475  9.396828
30   2025-01-02 05:00:00 -1.2736664  -1.458953857  9.347511
⋮    ⋮                   ⋮           ⋮            ⋮
8731 2025-12-30 18:00:00 -4.79200745  3.59104919   5.639503
8732 2025-12-30 19:00:00 -4.33520508  3.31842041   5.624367
8733 2025-12-30 20:00:00 -4.06106567  2.88200378  17.508881
8734 2025-12-30 21:00:00 -3.78321838  2.47007751  17.499603
8735 2025-12-30 22:00:00 -3.15728760  1.68859863  17.462006
8736 2025-12-30 23:00:00 -3.25012207  1.47756958  17.409027
8737 2025-12-31 00:00:00 -3.73449707  1.37515259  17.339935
8738 2025-12-31 01:00:00 -3.65496826  0.51901245  17.258148
8739 2025-12-31 02:00:00 -2.89140320 -0.32914734  17.160492
8740 2025-12-31 03:00:00 -1.74871826 -0.90039062  16.987640
8741 2025-12-31 04:00:00 -0.46391296 -1.15187073  16.807953
8742 2025-12-31 05:00:00  0.44990540 -1.25526428  16.646820
8743 2025-12-31 06:00:00  0.25561523 -0.91879272  16.501801
8744 2025-12-31 07:00:00 -0.46014404 -0.74626160  16.368500
8745 2025-12-31 08:00:00 -0.05056763 -0.47917175  16.244476
8746 2025-12-31 09:00:00  1.11471558  0.17048645  16.125336
8747 2025-12-31 10:00:00  1.61135864 -1.18273926  16.010590
8748 2025-12-31 11:00:00  1.03512573 -1.07684326  15.886574
8749 2025-12-31 12:00:00  0.56065369  0.52722168  15.758156
8750 2025-12-31 13:00:00 -0.45092773  1.14788818  15.616066
8751 2025-12-31 14:00:00 -1.16340637  1.56027222  15.366554
8752 2025-12-31 15:00:00 -2.59927368  2.26141357  15.142921
8753 2025-12-31 16:00:00 -2.49987793  1.32003784  14.967628
8754 2025-12-31 17:00:00 -2.61531067  0.57402039  14.822609
8755 2025-12-31 18:00:00 -2.57968140  0.72981262  14.695656
8756 2025-12-31 19:00:00 -2.88903809  1.60755920  14.579933
8757 2025-12-31 20:00:00 -2.69845581  2.51718140  14.468605
8758 2025-12-31 21:00:00 -0.89096069  1.96078491  14.357765
8759 2025-12-31 22:00:00  0.43595886  1.30622864  14.234230
8760 2025-12-31 23:00:00  0.93772888  0.01014709  14.074074
     pressao_media_mar direcao_media_onda coef_arrasto_onda
1    101335.4          150.3298           0.0008412045
2    101352.9          149.8325           0.0008383510
3    101354.5          149.3564           0.0008151513
4    101295.8          148.8990           0.0007729949
5    101251.7          148.5655           0.0007244621
6    101234.1          148.4647           0.0006870215
7    101198.0          148.6026           0.0006861491
8    101182.9          148.9300           0.0006851763
9    101189.1          149.3990           0.0006843021
10   101261.8          149.9300           0.0006831507
11   101323.4          150.5161           0.0006824150
12   101347.1          151.0315           0.0006828089
13   101380.1          151.5395           0.0006825393
14   101399.7          152.0368           0.0007382401
15   101382.8          152.4778           0.0008042757
16   101348.1          152.8453           0.0008544493
17   101324.1          153.1311           0.0008660804
18   101250.5          153.2934           0.0008323705
19   101204.5          153.3527           0.0008215085
20   101137.6          153.2701           0.0008303574
21   101139.4          153.0331           0.0008164290
22   101132.8          152.3785           0.0008633961
23   101136.4          151.3797           0.0008378467
24   101238.2          150.1601           0.0008116497
25   101254.3          148.6965           0.0008242335
26   101327.4          146.9465           0.0008150144
27   101286.0          144.9533           0.0007651835
28   101251.2          142.9726           0.0007230989
29   101174.0          141.1992           0.0006861479
30   101111.0          139.6813           0.0006851591
⋮    ⋮                 ⋮                  ⋮
8731 100890.3          140.0035           0.0009159511
8732 100932.1          141.6172           0.0008897071
8733 100935.1          143.5626           0.0008551853
8734 101039.8          146.4144           0.0008175815
8735 101008.8          149.9230           0.0007466022
8736 101091.4          153.8786           0.0007786809
8737 101194.1          157.6411           0.0007078215
8738 101290.1          160.8641           0.0006881021
8739 101277.0          163.5247           0.0006872492
8740 101264.5          165.7450           0.0006862660
8741 101210.2          167.5977           0.0006836883
8742 101100.6          169.1581           0.0006799977
8743 101086.4          170.4596           0.0006782392
8744 101102.6          171.5121           0.0006782603
8745 101127.2          172.3488           0.0006782189
8746 101203.1          173.0180           0.0006779642
8747 101219.7          173.5168           0.0006780056
8748 101262.1          173.8685           0.0006779083
8749 101330.4          174.0972           0.0006781088
8750 101330.9          174.2180           0.0006795132
8751 101337.3          174.2664           0.0007009245
8752 101266.6          174.2381           0.0007882104
8753 101220.7          174.1648           0.0008248843
8754 101071.2          174.0742           0.0007681062
8755 101031.8          173.9792           0.0007739540
8756 100959.0          173.8674           0.0007653476
8757 100927.4          173.7637           0.0006814105
8758 100975.6          173.6564           0.0006818185
8759 101070.2          173.6107           0.0006778208
8760 101127.8          173.5101           0.0006779630
     assimetria_espectral_onda inclinacao_media_quadratica_onda
1    0.01300998                0.003429498
2    0.01302727                0.003404713
3    0.01304291                0.003365618
4    0.01305439                0.003316987
5    0.01305060                0.003245468
6    0.01302527                0.003131984
7    0.01297547                0.002982760
8    0.01290855                0.002824101
9    0.01282473                0.002667530
10   0.01273299                0.002522519
11   0.01264228                0.002341528
12   0.01253483                0.002232658
13   0.01242289                0.002126784
14   0.01231603                0.002064782
15   0.01221640                0.002086096
16   0.01212708                0.002147138
17   0.01204030                0.002215802
18   0.01195460                0.002222483
19   0.01197778                0.002231121
20   0.01190518                0.002249812
21   0.01184608                0.002269841
22   0.01182673                0.002420525
23   0.01183352                0.002521845
24   0.01187013                0.002599856
25   0.01193889                0.002666589
26   0.01208065                0.002751449
27   0.01221787                0.002806745
28   0.01232868                0.002800077
29   0.01239700                0.002741109
30   0.01242778                0.002642247
⋮    ⋮                         ⋮
8731 0.021245345               0.002494744
8732 0.022275381               0.002684304
8733 0.003351499               0.002764827
8734 0.003550964               0.002792520
8735 0.003790847               0.002732946
8736 0.004081342               0.002742313
8737 0.004418921               0.002783044
8738 0.004806168               0.002851439
8739 0.005233526               0.002910180
8740 0.005713724               0.002934147
8741 0.006212350               0.002918125
8742 0.006707869               0.002875311
8743 0.007186130               0.002812142
8744 0.007641751               0.002731694
8745 0.008069865               0.002646344
8746 0.008465938               0.002565803
8747 0.008829236               0.002439908
8748 0.009167053               0.002365416
8749 0.009475261               0.002291542
8750 0.009758003               0.002219885
8751 0.010101654               0.002156680
8752 0.010401815               0.002226342
8753 0.010627739               0.002243512
8754 0.010793094               0.002229285
8755 0.010908384               0.002164675
8756 0.010984641               0.002124407
8757 0.011029039               0.002044173
8758 0.011047643               0.001953412
8759 0.011064239               0.001798966
8760 0.011098921               0.001742804
     altura_maxima_onda
1    2.337203
2    2.352866
3    2.365037
4    2.373783
5    2.378024
6    2.374745
7    2.364781
8    2.349154
9    2.329506
10   2.307474
11   2.280625
12   2.254695
13   2.227674
14   2.201085
15   2.177788
16   2.156590
17   2.135163
18   2.111593
19   2.120798
20   2.098122
21   2.077017
22   2.064839
23   2.052023
24   2.044648
25   2.037564
26   2.033274
27   2.030068
28   2.024197
29   2.012228
30   1.994649
⋮    ⋮
8731 1.296308
8732 1.361339
8733 1.413871
8734 1.497633
8735 1.593798
8736 1.707531
8737 1.836751
8738 1.981936
8739 2.137300
8740 2.296642
8741 2.453346
8742 2.606580
8743 2.753747
8744 2.887754
8745 3.009205
8746 3.116986
8747 3.209051
8748 3.290050
8749 3.356551
8750 3.408494
8751 3.448408
8752 3.483616
8753 3.500762
8754 3.506532
8755 3.499983
8756 3.485201
8757 3.459668
8758 3.426308
8759 3.385864
8760 3.341418

In [ ]:
write.csv(df_final, "df_final.csv", row.names = FALSE)